apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../../base/apps"

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    path: patch-namespace.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: k10
    path: patch-chart.yaml
