apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k10-export
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-k10-export
    namespace: kasten-io
  nfs:
    path: /mnt/storage/backups/kasten
    server: 192.168.1.220
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-custom
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: pvc-k10-export
  namespace: kasten-io
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-custom
  volumeMode: Filesystem
  volumeName: pv-k10-export