kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: generic-backup
spec:
  frequency: "@daily"
  retention:
    daily: 4
    weekly: 3
    monthly: 2
    yearly: 1
  selector:
    matchExpressions:
      - key: kanister.kasten.io/inject-sidecar
        operator: In
        values:
          - "true"
  actions:
    - action: backup
      backupParameters:
        filters:
          excludeResources:
            - matchExpressions:
                - key: kanister.kasten.io/ignore
                  operator: In
                  values:
                    - "true"
        profile:
          name: backblaze
          namespace: kasten-io
    - action: export
      exportParameters:
        frequency: "@daily"
        profile:
          name: backblaze
          namespace: kasten-io
        exportData:
          enabled: true
