apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    chart: ingress-nginx
    helm:
      values: |-
          extraArgs:
            default-ssl-certificate: "operators/wildcard-apps-hive-janz-digital-tls"
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.5
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
