- op: add
  path: /users/-
  value: "opentlc-mgr"
- op: add
  path: /users/-
  value: "user1"
- op: add
  path: /users/-
  value: "user2"
- op: add
  path: /users/-
  value: "user3"
- op: add
  path: /users/-
  value: "user4"
- op: add
  path: /users/-
  value: "user5"
- op: add
  path: /users/-
  value: "user6"
- op: add
  path: /users/-
  value: "user7"
- op: add
  path: /users/-
  value: "user8"
- op: add
  path: /users/-
  value: "user9"
- op: add
  path: /users/-
  value: "user10"
- op: add
  path: /users/-
  value: "user11"
- op: add
  path: /users/-
  value: "user12"
- op: add
  path: /users/-
  value: "user13"
- op: add
  path: /users/-
  value: "user14"
- op: add
  path: /users/-
  value: "user15"
- op: add
  path: /users/-
  value: "user16"
- op: add
  path: /users/-
  value: "user17"
- op: add
  path: /users/-
  value: "user18"
- op: add
  path: /users/-
  value: "user19"
- op: add
  path: /users/-
  value: "user20"
- op: add
  path: /users/-
  value: "user21"
- op: add
  path: /users/-
  value: "user22"
- op: add
  path: /users/-
  value: "user23"
- op: add
  path: /users/-
  value: "user24"
- op: add
  path: /users/-
  value: "user25"
- op: add
  path: /users/-
  value: "user26"
- op: add
  path: /users/-
  value: "user27"
- op: add
  path: /users/-
  value: "user28"
- op: add
  path: /users/-
  value: "user29"
- op: add
  path: /users/-
  value: "user30"
- op: add
  path: /users/-
  value: "user31"
- op: add
  path: /users/-
  value: "user32"
- op: add
  path: /users/-
  value: "user33"
- op: add
  path: /users/-
  value: "user34"
- op: add
  path: /users/-
  value: "user35"
- op: add
  path: /users/-
  value: "user36"
- op: add
  path: /users/-
  value: "user37"
- op: add
  path: /users/-
  value: "user38"
- op: add
  path: /users/-
  value: "user39"
