- op: add
  path: /users/-
  value: "kgresch@redhat.com"
- op: add
  path: /users/-
  value: "wschomburg"
- op: add
  path: /users/-
  value: "marcusne"
- op: add
  path: /users/-
  value: "marcoklaassen"
- op: add
  path: /users/-
  value: "gnunn@redhat.com"
