apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    repoURL: https://codecentric.github.io/helm-charts
    chart: keycloak
    targetRevision: 15.1.0
    helm:
      values: |-
        postgresql:
          global:
            storageClass: local-path
          primary:
        #    annotations:
        #      kanister.kasten.io/blueprint: postgres-bp
            labels:
              kanister.kasten.io/inject-sidecar: "true"

        extraEnv: |
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"

        ingress:
          enabled: true
          ingressClassName: "nginx"
          servicePort: http
          annotations:
            nginx.ingress.kubernetes.io/proxy-buffer-size: 128k

          rules:
            - host: 'sso.janz.digital'
              paths:
                - path: /
                  pathType: Prefix
            
            - host: 'sso.apps.hive.janz.digital'
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - 'sso.apps.hive.janz.digital'
                - 'sso.janz.digital'
              secretName: ""

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
