apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: cert-manager-operator
  namespace: operators
spec: 
  channel: stable
  name: cert-manager
  source: operatorhubio-catalog
  sourceNamespace: olm
