apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../../../manifests/argocd/apps/sealed-secrets-operator/private
  - ../../../manifests/argocd/apps/cert-manager/overlays/private
  - ../../../manifests/argocd/apps/nginx/base
  - ../../../manifests/argocd/apps/nfs-provisioner/base
  - ../../../manifests/argocd/apps/localpath-provisioner
  - ../../../manifests/argocd/apps/k10/base
  - ../../../manifests/argocd/apps/keycloak/base
  - ../../../manifests/argocd/apps/oauth2-proxy/base
  - ../../../manifests/argocd/apps/paperless-ng/overlays/private
  - ../../../manifests/argocd/apps/mariadb-homeassistant/base
  - ../../../manifests/argocd/apps/filebrowser/base
  - ../../../manifests/argocd/apps/vaultwarden/base
  - ../../../manifests/argocd/apps/frigate/base

resources:
  - ./cluster-apps-project.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      labelSelector: gitops.ownedBy=cluster-config
    path: patch-gitops-repo.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      labelSelector: gitops.ownedBy=cluster-config
    path: patch-target-revision.yaml
