apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-custom
  annotations:
    argocd.argoproj.io/sync-wave: "10"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
